name: test_data
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  twemoji: ^0.4.3
  google_fonts: ^4.0.3
  table_calendar: ^3.0.9
  provider: ^6.0.4

  page_transition: "^2.0.9"

  intl: ^0.18.1
  image_picker: ^0.8.7+4
  dotted_border: ^2.0.0+3
  dio: ^5.1.1
  multi_masked_formatter: ^1.0.0
  async: ^2.9.0
  fluttertoast: ^8.2.1
  kpostal: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700